POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "sumusb@naver.com", "password" : "test"}

### OK

POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "sumusb@naver.com", "password" : "test123"}

### PASSWORD not match

POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "sumusb@naver", "password" : "test"}

### username not Match

POST http://localhost:8080/formLogin
Content-Type: application/json

{"username" : "" , "password" : ""}

### loginDto empty


GET https://github.com/login/oauth/authorize
Content-Type: application/json

{"client_id" : "", "redirect_uri" : ""}

### authTest

POST https://github.com/login/oauth/access_token
Content-Type: application/json

{"client_id" : "", "client_secret" : "", "code" : ""}

### accessToken test

POST http://localhost:8080/api/signIn/github
Content-Type: application/json

{"token" : ""}

### signIntest